name: Schedule Test

on:
  workflow_dispatch: {}
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduled test
        run: echo "SCHEDULE WORKS"
